// Predefined list of skills with their categories
export const SKILLS_LIST = {
  'Programming Languages': [
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'C++',
    'Go',
    'Rust',
    'PHP',
    'Ruby',
    'Swift',
  ],
  'Frontend': [
    'React',
    'Vue',
    'Angular',
    'HTML5',
    'CSS3',
    'Sass',
    'Tailwind',
    'Next.js',
    'Redux',
  ],
  'Backend': [
    'Node.js',
    'Express',
    'Django',
    'Spring',
    'Laravel',
    'FastAPI',
    'GraphQL',
    'PostgreSQL',
    'MongoDB',
  ],
  'DevOps & Tools': [
    'Docker',
    'Kubernetes',
    'AWS',
    'Git',
    'Linux',
    'Nginx',
    'Jenkins',
    'Azure',
    'GCP',
  ],
};